version: '3.7'
services:
   app-server:
      image: brcz1n/server-app-tec502
      container_name: server-app
      ports:
         - 8000:8000
         - 8100:8100  
      networks:
         mynetwork:
            ipv4_address: 172.28.1.1
        
        
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
        