version: '3.7'
services:
   app-server:
      image: brcz1n/server-app-tec502
      container_name: server-app-brcz1n
      ports:
         - "8000:8000/tcp"
         - "8100:8100/udp"  
      network_mode: "host"